name: Release Message

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@b96a33520f8ad5e6dcdecee6f1212bdf88b16550 # v1.19.0
        with:
          webhook_url: ${{ secrets.RELEASE_WEBHOOK }}
          username: "LumioseCraft Announcements"
          content: "<@&1358056201144762641>"
          footer_timestamp: true
