name: Release Message

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.RELEASE_WEBHOOK }}
          username: "LumioseCraft Announcements"
          content: "<@&1358056201144762641>"
          footer_timestamp: true
