name: Update
on:
  workflow_dispatch:

jobs:
  parse-current-modpacks:
    name: Parse current modpacks to a list
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      modpack_folders: ${{ steps.list_modpacks.outputs.modpack_folders }}
      modpack_names: ${{ steps.list_modpacks.outputs.modpack_names }}
    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: List Modpacks
        id: list_modpacks
        run: |
          modpackFolders=()
          modpackNames=()
          for folder in packages/*/modpack; do
            if [ -d "$folder" ]; then
              if [ -e "$folder/pack.toml" ]; then
                modpackFolders+=("$folder")
                modpackNames+=($(grep -E 'name = ".*"' "$folder/pack.toml" | grep -o -E '".*"' | grep -o -E '[^"].*[^"]' | tr '[:upper:]' '[:lower:]'))
              fi
            fi
          done

          echo "modpack_folders=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${modpackFolders[@]}")" >> "$GITHUB_OUTPUT"
          echo "modpack_names=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${modpackNames[@]}")" >> "$GITHUB_OUTPUT"
      - name: Current detected modpacks
        run: |
          echo "::notice ::⚙ Current detected modpacks: ${{ steps.list_modpacks.outputs.modpack_names }}"

  update_mods:
    name: Update Mods
    runs-on: ubuntu-latest
    needs:
      - parse-current-modpacks
    if: ${{ (needs.parse-current-modpacks.outputs.modpack_folders) != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        modpack_path: ${{ fromJson(needs.parse-current-modpacks.outputs.modpack_folders) }}
        modpack_name: ${{ fromJson(needs.parse-current-modpacks.outputs.modpack_names) }}
    defaults:
      run:
        working-directory: ${{ matrix.modpack_path }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install nix
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31
      - name: Update Mods with Packwiz
        run: nix develop --command packwiz update -a -y
      - name: Push the updated mod list via a Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          branch: create-pull-request/patch-${{ matrix.modpack_name }}
          commit-message: "update(${{ matrix.modpack_name }}): updated mods"
          title: "update(${{ matrix.modpack_name }}): updated mods"
          body: >
            This PR is auto-generated by
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
